### PR TITLE
Add security specifications to API Operations

### PR DESCRIPTION
**Pull request by kushal-ti**
Allow users to specify Security specifications to their APIs

Before:
Screenshot 2023-05-16 at 7 22 16 PM

After:
Screenshot 2023-05-16 at 7 23 02 PM

Screenshot 2023-05-16 at 7 23 18 PM

Code implementation 

```python

from apispec import APISpec
from chalice_spec import ChaliceWithSpec, Docs, Operation, PydanticPlugin, Response

spec = APISpec(
    title="Spec", version="1.0.0", 
    openapi_version="3.0.2", plugins=[PydanticPlugin()]
)
bearer_auth = {"type": "http", "scheme": "bearer"}
spec.components.security_scheme("Auth", bearer_auth)

@app.route('/healthcheck', methods=['GET'], cors=True,
  docs=Docs(
    get=Operation(
      tags=['Health Check'], responses=[Response(code=HTTPStatus.OK, model=HealthCheckResponse)],
      description="Healthcheck endpoint, returns 'healthy' if service is online",
      summary="Healthcheck endpoint", security=[{"Auth": []}]
    )
  )
)
def healthcheck():
    return {'status': 'healthy'}
```

### CODE REVIEW

**Comment by kushal-ti** [comment]
Note: Other Security specification schemes like OAuth or OIDC should also work out of the box, since it's just rendering the JSON in an appropriate format

So, something like 
```python
oauth = {
  "type": "oauth2", 
  "flows": {
    "implicit": {
      "authorizationUrl": "<some-url>",
        "scopes": [
          "scope.read" : "Read scope",
          "scope.write" : "Write scope"
       ]
    }
  }
}
spec.components.security_scheme("OAuth", oauth)

@app.route('/healthcheck', methods=['GET'],
  docs=Docs(
    get=Operation(
      tags=['Health Check'], responses=[Response(code=HTTPStatus.OK, model=HealthCheckResponse)],
      description="Healthcheck endpoint, returns 'healthy' if service is online",
      summary="Healthcheck endpoint", security=[{"OAuth": ["scope.read", "scope.write"]}]
    )
  )
)
```
should work out of the box as well

**Comment by kushal-ti** [comment]
On further consideration, it would be better if the library were to define concrete security types, Bearer Auth, OAuth2, etc specified by the OAI 3 Spec, this way instead of referencing a string in the Operation() object, as was done here, it would be possible to reference an Object instantiation, providing better type safety. This can be considered a future improvement that can be added later

**Comment by kushal-ti** [comment]
@jakemwood sorry for the delay, have pulled from main and added tests for security, awaiting approval

**Comment by kushal-ti** [comment]
@jakemwood any updates on this ?

**Review by jakemwood — APPROVED** [review]

**Pull request merged**
